export interface StockInfo {
  symbol: string    // Yahoo Finance symbol
  nse: string       // NSE symbol
  company: string
  sector: string
}

export const STOCK_UNIVERSE: StockInfo[] = [
  // NIFTY 50
  { symbol: 'RELIANCE.NS', nse: 'RELIANCE', company: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'TCS.NS', nse: 'TCS', company: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK.NS', nse: 'HDFCBANK', company: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'INFY.NS', nse: 'INFY', company: 'Infosys', sector: 'IT' },
  { symbol: 'ICICIBANK.NS', nse: 'ICICIBANK', company: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'HINDUNILVR.NS', nse: 'HINDUNILVR', company: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'ITC.NS', nse: 'ITC', company: 'ITC Limited', sector: 'FMCG' },
  { symbol: 'SBIN.NS', nse: 'SBIN', company: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL.NS', nse: 'BHARTIARTL', company: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'KOTAKBANK.NS', nse: 'KOTAKBANK', company: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'LT.NS', nse: 'LT', company: 'Larsen & Toubro', sector: 'Infrastructure' },
  { symbol: 'AXISBANK.NS', nse: 'AXISBANK', company: 'Axis Bank', sector: 'Banking' },
  { symbol: 'ASIANPAINT.NS', nse: 'ASIANPAINT', company: 'Asian Paints', sector: 'Consumer' },
  { symbol: 'MARUTI.NS', nse: 'MARUTI', company: 'Maruti Suzuki', sector: 'Auto' },
  { symbol: 'SUNPHARMA.NS', nse: 'SUNPHARMA', company: 'Sun Pharma', sector: 'Pharma' },
  { symbol: 'TITAN.NS', nse: 'TITAN', company: 'Titan Company', sector: 'Consumer' },
  { symbol: 'BAJFINANCE.NS', nse: 'BAJFINANCE', company: 'Bajaj Finance', sector: 'NBFC' },
  { symbol: 'WIPRO.NS', nse: 'WIPRO', company: 'Wipro', sector: 'IT' },
  { symbol: 'ULTRACEMCO.NS', nse: 'ULTRACEMCO', company: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'NESTLEIND.NS', nse: 'NESTLEIND', company: 'Nestle India', sector: 'FMCG' },
  { symbol: 'POWERGRID.NS', nse: 'POWERGRID', company: 'Power Grid Corp', sector: 'Utilities' },
  { symbol: 'NTPC.NS', nse: 'NTPC', company: 'NTPC Limited', sector: 'Utilities' },
  { symbol: 'ONGC.NS', nse: 'ONGC', company: 'ONGC', sector: 'Energy' },
  { symbol: 'TECHM.NS', nse: 'TECHM', company: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'HCLTECH.NS', nse: 'HCLTECH', company: 'HCL Technologies', sector: 'IT' },
  { symbol: 'ADANIPORTS.NS', nse: 'ADANIPORTS', company: 'Adani Ports', sector: 'Logistics' },
  { symbol: 'COALINDIA.NS', nse: 'COALINDIA', company: 'Coal India', sector: 'Energy' },
  { symbol: 'BAJAJFINSV.NS', nse: 'BAJAJFINSV', company: 'Bajaj Finserv', sector: 'NBFC' },
  { symbol: 'TATASTEEL.NS', nse: 'TATASTEEL', company: 'Tata Steel', sector: 'Metals' },
  { symbol: 'JSWSTEEL.NS', nse: 'JSWSTEEL', company: 'JSW Steel', sector: 'Metals' },
  { symbol: 'HINDALCO.NS', nse: 'HINDALCO', company: 'Hindalco', sector: 'Metals' },
  { symbol: 'GRASIM.NS', nse: 'GRASIM', company: 'Grasim Industries', sector: 'Diversified' },
  { symbol: 'DIVISLAB.NS', nse: 'DIVISLAB', company: "Divi's Laboratories", sector: 'Pharma' },
  { symbol: 'DRREDDY.NS', nse: 'DRREDDY', company: "Dr. Reddy's Labs", sector: 'Pharma' },
  { symbol: 'CIPLA.NS', nse: 'CIPLA', company: 'Cipla', sector: 'Pharma' },
  { symbol: 'APOLLOHOSP.NS', nse: 'APOLLOHOSP', company: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'BAJAJ-AUTO.NS', nse: 'BAJAJ-AUTO', company: 'Bajaj Auto', sector: 'Auto' },
  { symbol: 'EICHERMOT.NS', nse: 'EICHERMOT', company: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'HEROMOTOCO.NS', nse: 'HEROMOTOCO', company: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'TATAMOTORS.NS', nse: 'TATAMOTORS', company: 'Tata Motors', sector: 'Auto' },
  { symbol: 'M&M.NS', nse: 'M&M', company: 'Mahindra & Mahindra', sector: 'Auto' },
  { symbol: 'INDUSINDBK.NS', nse: 'INDUSINDBK', company: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'BPCL.NS', nse: 'BPCL', company: 'BPCL', sector: 'Energy' },
  { symbol: 'TATACONSUM.NS', nse: 'TATACONSUM', company: 'Tata Consumer', sector: 'FMCG' },
  { symbol: 'BRITANNIA.NS', nse: 'BRITANNIA', company: 'Britannia Industries', sector: 'FMCG' },
  { symbol: 'SBILIFE.NS', nse: 'SBILIFE', company: 'SBI Life Insurance', sector: 'Insurance' },
  { symbol: 'HDFCLIFE.NS', nse: 'HDFCLIFE', company: 'HDFC Life Insurance', sector: 'Insurance' },
  { symbol: 'SHREECEM.NS', nse: 'SHREECEM', company: 'Shree Cement', sector: 'Cement' },
  { symbol: 'IOC.NS', nse: 'IOC', company: 'Indian Oil Corp', sector: 'Energy' },
  // NIFTY Next 50 + Midcap leaders
  { symbol: 'ZOMATO.NS', nse: 'ZOMATO', company: 'Zomato', sector: 'Consumer Tech' },
  { symbol: 'DMART.NS', nse: 'DMART', company: 'Avenue Supermarts', sector: 'Retail' },
  { symbol: 'PIDILITIND.NS', nse: 'PIDILITIND', company: 'Pidilite Industries', sector: 'Chemicals' },
  { symbol: 'HAVELLS.NS', nse: 'HAVELLS', company: 'Havells India', sector: 'Electricals' },
  { symbol: 'GODREJCP.NS', nse: 'GODREJCP', company: 'Godrej Consumer', sector: 'FMCG' },
  { symbol: 'MARICO.NS', nse: 'MARICO', company: 'Marico', sector: 'FMCG' },
  { symbol: 'DABUR.NS', nse: 'DABUR', company: 'Dabur India', sector: 'FMCG' },
  { symbol: 'COLPAL.NS', nse: 'COLPAL', company: 'Colgate-Palmolive', sector: 'FMCG' },
  { symbol: 'TATAPOWER.NS', nse: 'TATAPOWER', company: 'Tata Power', sector: 'Utilities' },
  { symbol: 'SAIL.NS', nse: 'SAIL', company: 'Steel Authority of India', sector: 'Metals' },
  { symbol: 'VEDL.NS', nse: 'VEDL', company: 'Vedanta', sector: 'Metals' },
  { symbol: 'BANKBARODA.NS', nse: 'BANKBARODA', company: 'Bank of Baroda', sector: 'Banking' },
  { symbol: 'PNB.NS', nse: 'PNB', company: 'Punjab National Bank', sector: 'Banking' },
  { symbol: 'CANBK.NS', nse: 'CANBK', company: 'Canara Bank', sector: 'Banking' },
  { symbol: 'FEDERALBNK.NS', nse: 'FEDERALBNK', company: 'Federal Bank', sector: 'Banking' },
  { symbol: 'IDFCFIRSTB.NS', nse: 'IDFCFIRSTB', company: 'IDFC First Bank', sector: 'Banking' },
  { symbol: 'CHOLAFIN.NS', nse: 'CHOLAFIN', company: 'Cholamandalam Finance', sector: 'NBFC' },
  { symbol: 'MUTHOOTFIN.NS', nse: 'MUTHOOTFIN', company: 'Muthoot Finance', sector: 'NBFC' },
  { symbol: 'RECLTD.NS', nse: 'RECLTD', company: 'REC Limited', sector: 'Finance' },
  { symbol: 'PFC.NS', nse: 'PFC', company: 'Power Finance Corp', sector: 'Finance' },
  { symbol: 'IRFC.NS', nse: 'IRFC', company: 'Indian Railway Finance', sector: 'Finance' },
  { symbol: 'NAUKRI.NS', nse: 'NAUKRI', company: 'Info Edge', sector: 'IT' },
  { symbol: 'IRCTC.NS', nse: 'IRCTC', company: 'IRCTC', sector: 'Travel' },
  { symbol: 'INDIGO.NS', nse: 'INDIGO', company: 'IndiGo Airlines', sector: 'Aviation' },
  // IT
  { symbol: 'MPHASIS.NS', nse: 'MPHASIS', company: 'Mphasis', sector: 'IT' },
  { symbol: 'LTIM.NS', nse: 'LTIM', company: 'LTIMindtree', sector: 'IT' },
  { symbol: 'PERSISTENT.NS', nse: 'PERSISTENT', company: 'Persistent Systems', sector: 'IT' },
  { symbol: 'COFORGE.NS', nse: 'COFORGE', company: 'Coforge', sector: 'IT' },
  { symbol: 'TATAELXSI.NS', nse: 'TATAELXSI', company: 'Tata Elxsi', sector: 'IT' },
  { symbol: 'OFSS.NS', nse: 'OFSS', company: 'Oracle Financial Services', sector: 'IT' },
  { symbol: 'KPITTECH.NS', nse: 'KPITTECH', company: 'KPIT Technologies', sector: 'IT' },
  // Pharma
  { symbol: 'AUROPHARMA.NS', nse: 'AUROPHARMA', company: 'Aurobindo Pharma', sector: 'Pharma' },
  { symbol: 'LUPIN.NS', nse: 'LUPIN', company: 'Lupin', sector: 'Pharma' },
  { symbol: 'BIOCON.NS', nse: 'BIOCON', company: 'Biocon', sector: 'Pharma' },
  { symbol: 'TORNTPHARM.NS', nse: 'TORNTPHARM', company: 'Torrent Pharma', sector: 'Pharma' },
  { symbol: 'ALKEM.NS', nse: 'ALKEM', company: 'Alkem Laboratories', sector: 'Pharma' },
  { symbol: 'LALPATHLAB.NS', nse: 'LALPATHLAB', company: 'Dr. Lal PathLabs', sector: 'Healthcare' },
  // Auto
  { symbol: 'MOTHERSON.NS', nse: 'MOTHERSON', company: 'Samvardhana Motherson', sector: 'Auto' },
  { symbol: 'BHARATFORG.NS', nse: 'BHARATFORG', company: 'Bharat Forge', sector: 'Auto' },
  { symbol: 'MRF.NS', nse: 'MRF', company: 'MRF', sector: 'Auto' },
  { symbol: 'APOLLOTYRE.NS', nse: 'APOLLOTYRE', company: 'Apollo Tyres', sector: 'Auto' },
  { symbol: 'TVSMOTOR.NS', nse: 'TVSMOTOR', company: 'TVS Motor', sector: 'Auto' },
  { symbol: 'ASHOKLEY.NS', nse: 'ASHOKLEY', company: 'Ashok Leyland', sector: 'Auto' },
  // Infra & Capital Goods
  { symbol: 'ABB.NS', nse: 'ABB', company: 'ABB India', sector: 'Industrials' },
  { symbol: 'SIEMENS.NS', nse: 'SIEMENS', company: 'Siemens India', sector: 'Industrials' },
  { symbol: 'BHEL.NS', nse: 'BHEL', company: 'BHEL', sector: 'Industrials' },
  { symbol: 'CUMMINSIND.NS', nse: 'CUMMINSIND', company: 'Cummins India', sector: 'Industrials' },
  { symbol: 'DLF.NS', nse: 'DLF', company: 'DLF', sector: 'Real Estate' },
  { symbol: 'GODREJPROP.NS', nse: 'GODREJPROP', company: 'Godrej Properties', sector: 'Real Estate' },
  // Chemicals
  { symbol: 'SRF.NS', nse: 'SRF', company: 'SRF Limited', sector: 'Chemicals' },
  { symbol: 'AARTIIND.NS', nse: 'AARTIIND', company: 'Aarti Industries', sector: 'Chemicals' },
  { symbol: 'DEEPAKNTR.NS', nse: 'DEEPAKNTR', company: 'Deepak Nitrite', sector: 'Chemicals' },
  { symbol: 'TATACHEM.NS', nse: 'TATACHEM', company: 'Tata Chemicals', sector: 'Chemicals' },
  // Consumer
  { symbol: 'TRENT.NS', nse: 'TRENT', company: 'Trent', sector: 'Retail' },
  { symbol: 'PAGEIND.NS', nse: 'PAGEIND', company: 'Page Industries', sector: 'Consumer' },
  { symbol: 'BATAINDIA.NS', nse: 'BATAINDIA', company: 'Bata India', sector: 'Consumer' },
  { symbol: 'JUBLFOOD.NS', nse: 'JUBLFOOD', company: 'Jubilant Foodworks', sector: 'QSR' },
  { symbol: 'VBL.NS', nse: 'VBL', company: 'Varun Beverages', sector: 'FMCG' },
  // Defence
  { symbol: 'HAL.NS', nse: 'HAL', company: 'Hindustan Aeronautics', sector: 'Defence' },
  { symbol: 'BEL.NS', nse: 'BEL', company: 'Bharat Electronics', sector: 'Defence' },
  // Adani Group
  { symbol: 'ADANIENT.NS', nse: 'ADANIENT', company: 'Adani Enterprises', sector: 'Diversified' },
  { symbol: 'ADANIGREEN.NS', nse: 'ADANIGREEN', company: 'Adani Green Energy', sector: 'Utilities' },
]
