export interface StockInfo {
  symbol: string
  nse: string
  company: string
  sector: string
}

export const STOCK_UNIVERSE: StockInfo[] = [
  // NIFTY 50
  { symbol: 'RELIANCE.NS', nse: 'RELIANCE', company: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'TCS.NS', nse: 'TCS', company: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK.NS', nse: 'HDFCBANK', company: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'INFY.NS', nse: 'INFY', company: 'Infosys', sector: 'IT' },
  { symbol: 'ICICIBANK.NS', nse: 'ICICIBANK', company: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'HINDUNILVR.NS', nse: 'HINDUNILVR', company: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'ITC.NS', nse: 'ITC', company: 'ITC Limited', sector: 'FMCG' },
  { symbol: 'SBIN.NS', nse: 'SBIN', company: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL.NS', nse: 'BHARTIARTL', company: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'KOTAKBANK.NS', nse: 'KOTAKBANK', company: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'LT.NS', nse: 'LT', company: 'Larsen & Toubro', sector: 'Infrastructure' },
  { symbol: 'AXISBANK.NS', nse: 'AXISBANK', company: 'Axis Bank', sector: 'Banking' },
  { symbol: 'ASIANPAINT.NS', nse: 'ASIANPAINT', company: 'Asian Paints', sector: 'Consumer' },
  { symbol: 'MARUTI.NS', nse: 'MARUTI', company: 'Maruti Suzuki', sector: 'Auto' },
  { symbol: 'SUNPHARMA.NS', nse: 'SUNPHARMA', company: 'Sun Pharma', sector: 'Pharma' },
  { symbol: 'TITAN.NS', nse: 'TITAN', company: 'Titan Company', sector: 'Consumer' },
  { symbol: 'BAJFINANCE.NS', nse: 'BAJFINANCE', company: 'Bajaj Finance', sector: 'NBFC' },
  { symbol: 'WIPRO.NS', nse: 'WIPRO', company: 'Wipro', sector: 'IT' },
  { symbol: 'ULTRACEMCO.NS', nse: 'ULTRACEMCO', company: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'NESTLEIND.NS', nse: 'NESTLEIND', company: 'Nestle India', sector: 'FMCG' },
  { symbol: 'POWERGRID.NS', nse: 'POWERGRID', company: 'Power Grid Corp', sector: 'Utilities' },
  { symbol: 'NTPC.NS', nse: 'NTPC', company: 'NTPC Limited', sector: 'Utilities' },
  { symbol: 'ONGC.NS', nse: 'ONGC', company: 'ONGC', sector: 'Energy' },
  { symbol: 'TECHM.NS', nse: 'TECHM', company: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'HCLTECH.NS', nse: 'HCLTECH', company: 'HCL Technologies', sector: 'IT' },
  { symbol: 'ADANIPORTS.NS', nse: 'ADANIPORTS', company: 'Adani Ports', sector: 'Logistics' },
  { symbol: 'COALINDIA.NS', nse: 'COALINDIA', company: 'Coal India', sector: 'Energy' },
  { symbol: 'BAJAJFINSV.NS', nse: 'BAJAJFINSV', company: 'Bajaj Finserv', sector: 'NBFC' },
  { symbol: 'TATASTEEL.NS', nse: 'TATASTEEL', company: 'Tata Steel', sector: 'Metals' },
  { symbol: 'JSWSTEEL.NS', nse: 'JSWSTEEL', company: 'JSW Steel', sector: 'Metals' },
  { symbol: 'HINDALCO.NS', nse: 'HINDALCO', company: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'GRASIM.NS', nse: 'GRASIM', company: 'Grasim Industries', sector: 'Diversified' },
  { symbol: 'DIVISLAB.NS', nse: 'DIVISLAB', company: "Divi's Laboratories", sector: 'Pharma' },
  { symbol: 'DRREDDY.NS', nse: 'DRREDDY', company: "Dr. Reddy's Labs", sector: 'Pharma' },
  { symbol: 'CIPLA.NS', nse: 'CIPLA', company: 'Cipla', sector: 'Pharma' },
  { symbol: 'APOLLOHOSP.NS', nse: 'APOLLOHOSP', company: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'BAJAJ-AUTO.NS', nse: 'BAJAJ-AUTO', company: 'Bajaj Auto', sector: 'Auto' },
  { symbol: 'EICHERMOT.NS', nse: 'EICHERMOT', company: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'HEROMOTOCO.NS', nse: 'HEROMOTOCO', company: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'TATAMOTORS.NS', nse: 'TATAMOTORS', company: 'Tata Motors', sector: 'Auto' },
  { symbol: 'M&M.NS', nse: 'M&M', company: 'Mahindra & Mahindra', sector: 'Auto' },
  { symbol: 'INDUSINDBK.NS', nse: 'INDUSINDBK', company: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'BPCL.NS', nse: 'BPCL', company: 'BPCL', sector: 'Energy' },
  { symbol: 'TATACONSUM.NS', nse: 'TATACONSUM', company: 'Tata Consumer', sector: 'FMCG' },
  { symbol: 'BRITANNIA.NS', nse: 'BRITANNIA', company: 'Britannia Industries', sector: 'FMCG' },
  { symbol: 'SBILIFE.NS', nse: 'SBILIFE', company: 'SBI Life Insurance', sector: 'Insurance' },
  { symbol: 'HDFCLIFE.NS', nse: 'HDFCLIFE', company: 'HDFC Life Insurance', sector: 'Insurance' },
  { symbol: 'SHREECEM.NS', nse: 'SHREECEM', company: 'Shree Cement', sector: 'Cement' },
  { symbol: 'IOC.NS', nse: 'IOC', company: 'Indian Oil Corp', sector: 'Energy' },
  { symbol: 'TATAPOWER.NS', nse: 'TATAPOWER', company: 'Tata Power', sector: 'Utilities' },
  // NIFTY Next 50
  { symbol: 'ADANIENT.NS', nse: 'ADANIENT', company: 'Adani Enterprises', sector: 'Diversified' },
  { symbol: 'ADANIGREEN.NS', nse: 'ADANIGREEN', company: 'Adani Green Energy', sector: 'Utilities' },
  { symbol: 'ADANIPORTS.NS', nse: 'ADANIPORTS', company: 'Adani Ports', sector: 'Logistics' },
  { symbol: 'ADANITRANS.NS', nse: 'ADANITRANS', company: 'Adani Transmission', sector: 'Utilities' },
  { symbol: 'ZOMATO.NS', nse: 'ZOMATO', company: 'Zomato', sector: 'Consumer Tech' },
  { symbol: 'DMART.NS', nse: 'DMART', company: 'Avenue Supermarts', sector: 'Retail' },
  { symbol: 'PIDILITIND.NS', nse: 'PIDILITIND', company: 'Pidilite Industries', sector: 'Chemicals' },
  { symbol: 'HAVELLS.NS', nse: 'HAVELLS', company: 'Havells India', sector: 'Electricals' },
  { symbol: 'GODREJCP.NS', nse: 'GODREJCP', company: 'Godrej Consumer', sector: 'FMCG' },
  { symbol: 'MARICO.NS', nse: 'MARICO', company: 'Marico', sector: 'FMCG' },
  { symbol: 'DABUR.NS', nse: 'DABUR', company: 'Dabur India', sector: 'FMCG' },
  { symbol: 'COLPAL.NS', nse: 'COLPAL', company: 'Colgate-Palmolive', sector: 'FMCG' },
  { symbol: 'SAIL.NS', nse: 'SAIL', company: 'Steel Authority of India', sector: 'Metals' },
  { symbol: 'VEDL.NS', nse: 'VEDL', company: 'Vedanta', sector: 'Metals' },
  { symbol: 'BANKBARODA.NS', nse: 'BANKBARODA', company: 'Bank of Baroda', sector: 'Banking' },
  { symbol: 'PNB.NS', nse: 'PNB', company: 'Punjab National Bank', sector: 'Banking' },
  { symbol: 'CANBK.NS', nse: 'CANBK', company: 'Canara Bank', sector: 'Banking' },
  { symbol: 'FEDERALBNK.NS', nse: 'FEDERALBNK', company: 'Federal Bank', sector: 'Banking' },
  { symbol: 'IDFCFIRSTB.NS', nse: 'IDFCFIRSTB', company: 'IDFC First Bank', sector: 'Banking' },
  { symbol: 'BANDHANBNK.NS', nse: 'BANDHANBNK', company: 'Bandhan Bank', sector: 'Banking' },
  { symbol: 'RBLBANK.NS', nse: 'RBLBANK', company: 'RBL Bank', sector: 'Banking' },
  { symbol: 'CHOLAFIN.NS', nse: 'CHOLAFIN', company: 'Cholamandalam Finance', sector: 'NBFC' },
  { symbol: 'MUTHOOTFIN.NS', nse: 'MUTHOOTFIN', company: 'Muthoot Finance', sector: 'NBFC' },
  { symbol: 'MANAPPURAM.NS', nse: 'MANAPPURAM', company: 'Manappuram Finance', sector: 'NBFC' },
  { symbol: 'LICHSGFIN.NS', nse: 'LICHSGFIN', company: 'LIC Housing Finance', sector: 'Finance' },
  { symbol: 'RECLTD.NS', nse: 'RECLTD', company: 'REC Limited', sector: 'Finance' },
  { symbol: 'PFC.NS', nse: 'PFC', company: 'Power Finance Corp', sector: 'Finance' },
  { symbol: 'IRFC.NS', nse: 'IRFC', company: 'Indian Railway Finance', sector: 'Finance' },
  { symbol: 'NAUKRI.NS', nse: 'NAUKRI', company: 'Info Edge', sector: 'IT' },
  { symbol: 'IRCTC.NS', nse: 'IRCTC', company: 'IRCTC', sector: 'Travel' },
  { symbol: 'INDIGO.NS', nse: 'INDIGO', company: 'IndiGo Airlines', sector: 'Aviation' },
  { symbol: 'DLF.NS', nse: 'DLF', company: 'DLF Limited', sector: 'Real Estate' },
  { symbol: 'GODREJPROP.NS', nse: 'GODREJPROP', company: 'Godrej Properties', sector: 'Real Estate' },
  { symbol: 'OBEROIRLTY.NS', nse: 'OBEROIRLTY', company: 'Oberoi Realty', sector: 'Real Estate' },
  { symbol: 'PRESTIGE.NS', nse: 'PRESTIGE', company: 'Prestige Estates', sector: 'Real Estate' },
  { symbol: 'BRIGADE.NS', nse: 'BRIGADE', company: 'Brigade Enterprises', sector: 'Real Estate' },
  { symbol: 'PHOENIXLTD.NS', nse: 'PHOENIXLTD', company: 'Phoenix Mills', sector: 'Real Estate' },
  // IT & Tech
  { symbol: 'MPHASIS.NS', nse: 'MPHASIS', company: 'Mphasis', sector: 'IT' },
  { symbol: 'LTIM.NS', nse: 'LTIM', company: 'LTIMindtree', sector: 'IT' },
  { symbol: 'PERSISTENT.NS', nse: 'PERSISTENT', company: 'Persistent Systems', sector: 'IT' },
  { symbol: 'COFORGE.NS', nse: 'COFORGE', company: 'Coforge', sector: 'IT' },
  { symbol: 'TATAELXSI.NS', nse: 'TATAELXSI', company: 'Tata Elxsi', sector: 'IT' },
  { symbol: 'OFSS.NS', nse: 'OFSS', company: 'Oracle Financial Services', sector: 'IT' },
  { symbol: 'KPITTECH.NS', nse: 'KPITTECH', company: 'KPIT Technologies', sector: 'IT' },
  { symbol: 'ZENSAR.NS', nse: 'ZENSAR', company: 'Zensar Technologies', sector: 'IT' },
  { symbol: 'MASTEK.NS', nse: 'MASTEK', company: 'Mastek', sector: 'IT' },
  { symbol: 'TANLA.NS', nse: 'TANLA', company: 'Tanla Platforms', sector: 'IT' },
  { symbol: 'LATENTVIEW.NS', nse: 'LATENTVIEW', company: 'LatentView Analytics', sector: 'IT' },
  { symbol: 'HAPPYFORGE.NS', nse: 'HAPPYFORGE', company: 'Happy Forgings', sector: 'Auto' },
  { symbol: 'ROUTE.NS', nse: 'ROUTE', company: 'Route Mobile', sector: 'IT' },
  { symbol: 'INTELLECT.NS', nse: 'INTELLECT', company: 'Intellect Design Arena', sector: 'IT' },
  { symbol: 'NEWGEN.NS', nse: 'NEWGEN', company: 'Newgen Software', sector: 'IT' },
  // Pharma & Healthcare
  { symbol: 'AUROPHARMA.NS', nse: 'AUROPHARMA', company: 'Aurobindo Pharma', sector: 'Pharma' },
  { symbol: 'LUPIN.NS', nse: 'LUPIN', company: 'Lupin', sector: 'Pharma' },
  { symbol: 'BIOCON.NS', nse: 'BIOCON', company: 'Biocon', sector: 'Pharma' },
  { symbol: 'TORNTPHARM.NS', nse: 'TORNTPHARM', company: 'Torrent Pharma', sector: 'Pharma' },
  { symbol: 'ALKEM.NS', nse: 'ALKEM', company: 'Alkem Laboratories', sector: 'Pharma' },
  { symbol: 'IPCALAB.NS', nse: 'IPCALAB', company: 'IPCA Laboratories', sector: 'Pharma' },
  { symbol: 'GLENMARK.NS', nse: 'GLENMARK', company: 'Glenmark Pharma', sector: 'Pharma' },
  { symbol: 'LALPATHLAB.NS', nse: 'LALPATHLAB', company: 'Dr. Lal PathLabs', sector: 'Healthcare' },
  { symbol: 'METROPOLIS.NS', nse: 'METROPOLIS', company: 'Metropolis Healthcare', sector: 'Healthcare' },
  { symbol: 'FORTIS.NS', nse: 'FORTIS', company: 'Fortis Healthcare', sector: 'Healthcare' },
  { symbol: 'MAXHEALTH.NS', nse: 'MAXHEALTH', company: 'Max Healthcare', sector: 'Healthcare' },
  { symbol: 'AARTIIND.NS', nse: 'AARTIIND', company: 'Aarti Industries', sector: 'Chemicals' },
  { symbol: 'ABBOTINDIA.NS', nse: 'ABBOTINDIA', company: 'Abbott India', sector: 'Pharma' },
  { symbol: 'PFIZER.NS', nse: 'PFIZER', company: 'Pfizer India', sector: 'Pharma' },
  { symbol: 'SANOFI.NS', nse: 'SANOFI', company: 'Sanofi India', sector: 'Pharma' },
  { symbol: 'GLAXO.NS', nse: 'GLAXO', company: 'GlaxoSmithKline Pharma', sector: 'Pharma' },
  { symbol: 'AJANTPHARM.NS', nse: 'AJANTPHARM', company: 'Ajanta Pharma', sector: 'Pharma' },
  { symbol: 'GRANULES.NS', nse: 'GRANULES', company: 'Granules India', sector: 'Pharma' },
  { symbol: 'NATCOPHARM.NS', nse: 'NATCOPHARM', company: 'Natco Pharma', sector: 'Pharma' },
  { symbol: 'LAURUSLABS.NS', nse: 'LAURUSLABS', company: 'Laurus Labs', sector: 'Pharma' },
  { symbol: 'SUVEN.NS', nse: 'SUVEN', company: 'Suven Pharmaceuticals', sector: 'Pharma' },
  // Auto & Auto Ancillary
  { symbol: 'MOTHERSON.NS', nse: 'MOTHERSON', company: 'Samvardhana Motherson', sector: 'Auto' },
  { symbol: 'BHARATFORG.NS', nse: 'BHARATFORG', company: 'Bharat Forge', sector: 'Auto' },
  { symbol: 'MRF.NS', nse: 'MRF', company: 'MRF', sector: 'Auto' },
  { symbol: 'APOLLOTYRE.NS', nse: 'APOLLOTYRE', company: 'Apollo Tyres', sector: 'Auto' },
  { symbol: 'CEATLTD.NS', nse: 'CEATLTD', company: 'CEAT', sector: 'Auto' },
  { symbol: 'EXIDEIND.NS', nse: 'EXIDEIND', company: 'Exide Industries', sector: 'Auto' },
  { symbol: 'TVSMOTOR.NS', nse: 'TVSMOTOR', company: 'TVS Motor', sector: 'Auto' },
  { symbol: 'ASHOKLEY.NS', nse: 'ASHOKLEY', company: 'Ashok Leyland', sector: 'Auto' },
  { symbol: 'ESCORTS.NS', nse: 'ESCORTS', company: 'Escorts Kubota', sector: 'Auto' },
  { symbol: 'BOSCHLTD.NS', nse: 'BOSCHLTD', company: 'Bosch India', sector: 'Auto' },
  { symbol: 'SUNDRMFAST.NS', nse: 'SUNDRMFAST', company: 'Sundram Fasteners', sector: 'Auto' },
  { symbol: 'GABRIEL.NS', nse: 'GABRIEL', company: 'Gabriel India', sector: 'Auto' },
  { symbol: 'SUPRAJIT.NS', nse: 'SUPRAJIT', company: 'Suprajit Engineering', sector: 'Auto' },
  { symbol: 'ENDURANCE.NS', nse: 'ENDURANCE', company: 'Endurance Technologies', sector: 'Auto' },
  { symbol: 'CRAFTSMAN.NS', nse: 'CRAFTSMAN', company: 'Craftsman Automation', sector: 'Auto' },
  { symbol: 'TIINDIA.NS', nse: 'TIINDIA', company: 'Tube Investments', sector: 'Auto' },
  { symbol: 'SWARAJENG.NS', nse: 'SWARAJENG', company: 'Swaraj Engines', sector: 'Auto' },
  { symbol: 'AMARAJABAT.NS', nse: 'AMARAJABAT', company: 'Amara Raja Energy', sector: 'Auto' },
  // Industrials & Capital Goods
  { symbol: 'ABB.NS', nse: 'ABB', company: 'ABB India', sector: 'Industrials' },
  { symbol: 'SIEMENS.NS', nse: 'SIEMENS', company: 'Siemens India', sector: 'Industrials' },
  { symbol: 'BHEL.NS', nse: 'BHEL', company: 'BHEL', sector: 'Industrials' },
  { symbol: 'CUMMINSIND.NS', nse: 'CUMMINSIND', company: 'Cummins India', sector: 'Industrials' },
  { symbol: 'THERMAX.NS', nse: 'THERMAX', company: 'Thermax', sector: 'Industrials' },
  { symbol: 'KEC.NS', nse: 'KEC', company: 'KEC International', sector: 'Industrials' },
  { symbol: 'KALPATPOWR.NS', nse: 'KALPATPOWR', company: 'Kalpataru Projects', sector: 'Industrials' },
  { symbol: 'GRINDWELL.NS', nse: 'GRINDWELL', company: 'Grindwell Norton', sector: 'Industrials' },
  { symbol: 'TIMKEN.NS', nse: 'TIMKEN', company: 'Timken India', sector: 'Industrials' },
  { symbol: 'SCHAEFFLER.NS', nse: 'SCHAEFFLER', company: 'Schaeffler India', sector: 'Industrials' },
  { symbol: 'SKFINDIA.NS', nse: 'SKFINDIA', company: 'SKF India', sector: 'Industrials' },
  { symbol: 'VOLTAMP.NS', nse: 'VOLTAMP', company: 'Voltamp Transformers', sector: 'Industrials' },
  { symbol: 'AIAENG.NS', nse: 'AIAENG', company: 'AIA Engineering', sector: 'Industrials' },
  { symbol: 'ELGIEQUIP.NS', nse: 'ELGIEQUIP', company: 'Elgi Equipments', sector: 'Industrials' },
  { symbol: 'BHARAT ELEC', nse: 'BEL', company: 'Bharat Electronics', sector: 'Defence' },
  { symbol: 'HAL.NS', nse: 'HAL', company: 'Hindustan Aeronautics', sector: 'Defence' },
  { symbol: 'BEL.NS', nse: 'BEL', company: 'Bharat Electronics', sector: 'Defence' },
  { symbol: 'BEML.NS', nse: 'BEML', company: 'BEML', sector: 'Defence' },
  { symbol: 'COCHINSHIP.NS', nse: 'COCHINSHIP', company: 'Cochin Shipyard', sector: 'Defence' },
  { symbol: 'MAZDOCK.NS', nse: 'MAZDOCK', company: 'Mazagon Dock', sector: 'Defence' },
  { symbol: 'GRSE.NS', nse: 'GRSE', company: 'Garden Reach Shipbuilders', sector: 'Defence' },
  { symbol: 'RVNL.NS', nse: 'RVNL', company: 'Rail Vikas Nigam', sector: 'Infrastructure' },
  { symbol: 'IRCON.NS', nse: 'IRCON', company: 'Ircon International', sector: 'Infrastructure' },
  { symbol: 'NCC.NS', nse: 'NCC', company: 'NCC Limited', sector: 'Infrastructure' },
  { symbol: 'KNRCON.NS', nse: 'KNRCON', company: 'KNR Constructions', sector: 'Infrastructure' },
  { symbol: 'IRB.NS', nse: 'IRB', company: 'IRB Infrastructure', sector: 'Infrastructure' },
  { symbol: 'GMRINFRA.NS', nse: 'GMRINFRA', company: 'GMR Airports', sector: 'Infrastructure' },
  { symbol: 'AHLUCONT.NS', nse: 'AHLUCONT', company: 'Ahluwalia Contracts', sector: 'Infrastructure' },
  // Chemicals & Specialty
  { symbol: 'SRF.NS', nse: 'SRF', company: 'SRF Limited', sector: 'Chemicals' },
  { symbol: 'DEEPAKNTR.NS', nse: 'DEEPAKNTR', company: 'Deepak Nitrite', sector: 'Chemicals' },
  { symbol: 'TATACHEM.NS', nse: 'TATACHEM', company: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'NAVINFLUOR.NS', nse: 'NAVINFLUOR', company: 'Navin Fluorine', sector: 'Chemicals' },
  { symbol: 'ALKYLAMINE.NS', nse: 'ALKYLAMINE', company: 'Alkyl Amines', sector: 'Chemicals' },
  { symbol: 'VINATI.NS', nse: 'VINATI', company: 'Vinati Organics', sector: 'Chemicals' },
  { symbol: 'CLEAN.NS', nse: 'CLEAN', company: 'Clean Science & Technology', sector: 'Chemicals' },
  { symbol: 'NOCIL.NS', nse: 'NOCIL', company: 'NOCIL', sector: 'Chemicals' },
  { symbol: 'FINEORG.NS', nse: 'FINEORG', company: 'Fine Organic Industries', sector: 'Chemicals' },
  { symbol: 'GALAXYSURF.NS', nse: 'GALAXYSURF', company: 'Galaxy Surfactants', sector: 'Chemicals' },
  { symbol: 'PCBL.NS', nse: 'PCBL', company: 'PCBL', sector: 'Chemicals' },
  { symbol: 'TATACHEM.NS', nse: 'TATACHEM', company: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'SUDARSCHEM.NS', nse: 'SUDARSCHEM', company: 'Sudarshan Chemical', sector: 'Chemicals' },
  { symbol: 'IGPL.NS', nse: 'IGPL', company: 'IG Petrochemicals', sector: 'Chemicals' },
  // FMCG & Consumer
  { symbol: 'VBL.NS', nse: 'VBL', company: 'Varun Beverages', sector: 'FMCG' },
  { symbol: 'RADICO.NS', nse: 'RADICO', company: 'Radico Khaitan', sector: 'FMCG' },
  { symbol: 'UNITDSPR.NS', nse: 'UNITDSPR', company: 'United Spirits', sector: 'FMCG' },
  { symbol: 'EMAMILTD.NS', nse: 'EMAMILTD', company: 'Emami', sector: 'FMCG' },
  { symbol: 'JYOTHYLAB.NS', nse: 'JYOTHYLAB', company: 'Jyothy Labs', sector: 'FMCG' },
  { symbol: 'BAJAJCON.NS', nse: 'BAJAJCON', company: 'Bajaj Consumer Care', sector: 'FMCG' },
  { symbol: 'TRENT.NS', nse: 'TRENT', company: 'Trent', sector: 'Retail' },
  { symbol: 'PAGEIND.NS', nse: 'PAGEIND', company: 'Page Industries', sector: 'Consumer' },
  { symbol: 'BATAINDIA.NS', nse: 'BATAINDIA', company: 'Bata India', sector: 'Consumer' },
  { symbol: 'RELAXO.NS', nse: 'RELAXO', company: 'Relaxo Footwears', sector: 'Consumer' },
  { symbol: 'MANYAVAR.NS', nse: 'MANYAVAR', company: 'Vedant Fashions', sector: 'Consumer' },
  { symbol: 'SHOPERSTOP.NS', nse: 'SHOPERSTOP', company: "Shopper's Stop", sector: 'Retail' },
  { symbol: 'VMART.NS', nse: 'VMART', company: 'V-Mart Retail', sector: 'Retail' },
  { symbol: 'JUBLFOOD.NS', nse: 'JUBLFOOD', company: 'Jubilant Foodworks', sector: 'QSR' },
  { symbol: 'DEVYANI.NS', nse: 'DEVYANI', company: 'Devyani International', sector: 'QSR' },
  { symbol: 'WESTLIFE.NS', nse: 'WESTLIFE', company: 'Westlife Foodworld', sector: 'QSR' },
  { symbol: 'SAPPHIRE.NS', nse: 'SAPPHIRE', company: 'Sapphire Foods', sector: 'QSR' },
  // Metals & Mining
  { symbol: 'JINDALSTEL.NS', nse: 'JINDALSTEL', company: 'Jindal Steel & Power', sector: 'Metals' },
  { symbol: 'NMDC.NS', nse: 'NMDC', company: 'NMDC', sector: 'Metals' },
  { symbol: 'MOIL.NS', nse: 'MOIL', company: 'MOIL', sector: 'Metals' },
  { symbol: 'NATIONALUM.NS', nse: 'NATIONALUM', company: 'National Aluminium', sector: 'Metals' },
  { symbol: 'HINDZINC.NS', nse: 'HINDZINC', company: 'Hindustan Zinc', sector: 'Metals' },
  { symbol: 'WELCORP.NS', nse: 'WELCORP', company: 'Welspun Corp', sector: 'Metals' },
  { symbol: 'RATNAMANI.NS', nse: 'RATNAMANI', company: 'Ratnamani Metals', sector: 'Metals' },
  { symbol: 'APL APOLLO', nse: 'APLAPOLLO', company: 'APL Apollo Tubes', sector: 'Metals' },
  { symbol: 'APLAPOLLO.NS', nse: 'APLAPOLLO', company: 'APL Apollo Tubes', sector: 'Metals' },
  { symbol: 'JSWINFRA.NS', nse: 'JSWINFRA', company: 'JSW Infrastructure', sector: 'Logistics' },
  // Utilities & Energy
  { symbol: 'TORNTPOWER.NS', nse: 'TORNTPOWER', company: 'Torrent Power', sector: 'Utilities' },
  { symbol: 'CESC.NS', nse: 'CESC', company: 'CESC', sector: 'Utilities' },
  { symbol: 'ADANIGREEN.NS', nse: 'ADANIGREEN', company: 'Adani Green Energy', sector: 'Utilities' },
  { symbol: 'INOXWIND.NS', nse: 'INOXWIND', company: 'Inox Wind', sector: 'Utilities' },
  { symbol: 'SUZLON.NS', nse: 'SUZLON', company: 'Suzlon Energy', sector: 'Utilities' },
  { symbol: 'RPOWER.NS', nse: 'RPOWER', company: 'Reliance Power', sector: 'Utilities' },
  { symbol: 'NHPC.NS', nse: 'NHPC', company: 'NHPC', sector: 'Utilities' },
  { symbol: 'SJVN.NS', nse: 'SJVN', company: 'SJVN', sector: 'Utilities' },
  { symbol: 'THERMAX.NS', nse: 'THERMAX', company: 'Thermax', sector: 'Industrials' },
  { symbol: 'GAIL.NS', nse: 'GAIL', company: 'GAIL India', sector: 'Energy' },
  { symbol: 'PETRONET.NS', nse: 'PETRONET', company: 'Petronet LNG', sector: 'Energy' },
  { symbol: 'HINDPETRO.NS', nse: 'HINDPETRO', company: 'Hindustan Petroleum', sector: 'Energy' },
  { symbol: 'MRPL.NS', nse: 'MRPL', company: 'MRPL', sector: 'Energy' },
  { symbol: 'CASTROLIND.NS', nse: 'CASTROLIND', company: 'Castrol India', sector: 'Energy' },
  // Telecom & Media
  { symbol: 'TATACOMM.NS', nse: 'TATACOMM', company: 'Tata Communications', sector: 'Telecom' },
  { symbol: 'IDEA.NS', nse: 'IDEA', company: 'Vodafone Idea', sector: 'Telecom' },
  { symbol: 'ZEEL.NS', nse: 'ZEEL', company: 'Zee Entertainment', sector: 'Media' },
  { symbol: 'PVRINOX.NS', nse: 'PVRINOX', company: 'PVR INOX', sector: 'Media' },
  { symbol: 'NAZARA.NS', nse: 'NAZARA', company: 'Nazara Technologies', sector: 'Media' },
  { symbol: 'NETWORK18.NS', nse: 'NETWORK18', company: 'Network18 Media', sector: 'Media' },
  { symbol: 'SUNTV.NS', nse: 'SUNTV', company: 'Sun TV Network', sector: 'Media' },
  // Insurance
  { symbol: 'ICICIGI.NS', nse: 'ICICIGI', company: 'ICICI Lombard', sector: 'Insurance' },
  { symbol: 'ICICIPRULI.NS', nse: 'ICICIPRULI', company: 'ICICI Prudential Life', sector: 'Insurance' },
  { symbol: 'STARHEALTH.NS', nse: 'STARHEALTH', company: 'Star Health Insurance', sector: 'Insurance' },
  { symbol: 'GICRE.NS', nse: 'GICRE', company: 'General Insurance Corp', sector: 'Insurance' },
  { symbol: 'NIACL.NS', nse: 'NIACL', company: 'New India Assurance', sector: 'Insurance' },
  // Logistics
  { symbol: 'CONCOR.NS', nse: 'CONCOR', company: 'Container Corp of India', sector: 'Logistics' },
  { symbol: 'BLUEDART.NS', nse: 'BLUEDART', company: 'Blue Dart Express', sector: 'Logistics' },
  { symbol: 'DELHIVERY.NS', nse: 'DELHIVERY', company: 'Delhivery', sector: 'Logistics' },
  { symbol: 'MAHLOG.NS', nse: 'MAHLOG', company: 'Mahindra Logistics', sector: 'Logistics' },
  { symbol: 'AEGISCHEM.NS', nse: 'AEGISCHEM', company: 'Aegis Logistics', sector: 'Logistics' },
  // New Age & Fintech
  { symbol: 'PAYTM.NS', nse: 'PAYTM', company: 'Paytm', sector: 'Fintech' },
  { symbol: 'POLICYBZR.NS', nse: 'POLICYBZR', company: 'PB Fintech', sector: 'Fintech' },
  { symbol: 'NYKAA.NS', nse: 'NYKAA', company: 'FSN E-Commerce (Nykaa)', sector: 'E-Commerce' },
  { symbol: 'CARTRADE.NS', nse: 'CARTRADE', company: 'CarTrade Tech', sector: 'E-Commerce' },
  { symbol: 'EASEMYTRIP.NS', nse: 'EASEMYTRIP', company: 'Easy Trip Planners', sector: 'Travel' },
  { symbol: 'IXIGO.NS', nse: 'IXIGO', company: 'Le Travenues (ixigo)', sector: 'Travel' },
  { symbol: 'JUSTDIAL.NS', nse: 'JUSTDIAL', company: 'Just Dial', sector: 'IT' },
  { symbol: 'INDIGOPNTS.NS', nse: 'INDIGOPNTS', company: 'Indigo Paints', sector: 'Consumer' },
  { symbol: 'BERGEPAINT.NS', nse: 'BERGEPAINT', company: 'Berger Paints', sector: 'Consumer' },
  { symbol: 'KANSAINER.NS', nse: 'KANSAINER', company: 'Kansai Nerolac', sector: 'Consumer' },
  { symbol: 'AKZOINDIA.NS', nse: 'AKZOINDIA', company: 'Akzo Nobel India', sector: 'Consumer' },
  // Electricals & Electronics
  { symbol: 'VOLTAS.NS', nse: 'VOLTAS', company: 'Voltas', sector: 'Electricals' },
  { symbol: 'BLUESTARCO.NS', nse: 'BLUESTARCO', company: 'Blue Star', sector: 'Electricals' },
  { symbol: 'AMBER.NS', nse: 'AMBER', company: 'Amber Enterprises', sector: 'Electricals' },
  { symbol: 'DIXON.NS', nse: 'DIXON', company: 'Dixon Technologies', sector: 'Electricals' },
  { symbol: 'KAYNES.NS', nse: 'KAYNES', company: 'Kaynes Technology', sector: 'Electricals' },
  { symbol: 'SYRMA.NS', nse: 'SYRMA', company: 'Syrma SGS Technology', sector: 'Electricals' },
  { symbol: 'WHIRLPOOL.NS', nse: 'WHIRLPOOL', company: 'Whirlpool India', sector: 'Electricals' },
  // Agriculture & Agrochem
  { symbol: 'UPL.NS', nse: 'UPL', company: 'UPL', sector: 'Agrochem' },
  { symbol: 'PIIND.NS', nse: 'PIIND', company: 'PI Industries', sector: 'Agrochem' },
  { symbol: 'RALLIS.NS', nse: 'RALLIS', company: 'Rallis India', sector: 'Agrochem' },
  { symbol: 'DHANUKA.NS', nse: 'DHANUKA', company: 'Dhanuka Agritech', sector: 'Agrochem' },
  { symbol: 'SUMICHEM.NS', nse: 'SUMICHEM', company: 'Sumitomo Chemical India', sector: 'Agrochem' },
  { symbol: 'GODREJAGRO.NS', nse: 'GODREJAGRO', company: 'Godrej Agrovet', sector: 'Agrochem' },
  { symbol: 'AVANTIFEED.NS', nse: 'AVANTIFEED', company: 'Avanti Feeds', sector: 'Agrochem' },
  { symbol: 'KRBL.NS', nse: 'KRBL', company: 'KRBL', sector: 'Agriculture' },
  { symbol: 'LT FOODS', nse: 'LTFOODS', company: 'LT Foods', sector: 'Agriculture' },
  { symbol: 'LTFOODS.NS', nse: 'LTFOODS', company: 'LT Foods', sector: 'Agriculture' },
  // Cement
  { symbol: 'AMBUJACEM.NS', nse: 'AMBUJACEM', company: 'Ambuja Cements', sector: 'Cement' },
  { symbol: 'ACC.NS', nse: 'ACC', company: 'ACC', sector: 'Cement' },
  { symbol: 'RAMCOCEM.NS', nse: 'RAMCOCEM', company: 'Ramco Cements', sector: 'Cement' },
  { symbol: 'JKCEMENT.NS', nse: 'JKCEMENT', company: 'JK Cement', sector: 'Cement' },
  { symbol: 'HEIDELBERG.NS', nse: 'HEIDELBERG', company: 'HeidelbergCement India', sector: 'Cement' },
  { symbol: 'DALMIACEM.NS', nse: 'DALMIACEM', company: 'Dalmia Bharat', sector: 'Cement' },
  { symbol: 'BIRLACORPN.NS', nse: 'BIRLACORPN', company: 'Birla Corporation', sector: 'Cement' },
  { symbol: 'JKLAKSHMI.NS', nse: 'JKLAKSHMI', company: 'JK Lakshmi Cement', sector: 'Cement' },
  // Textiles
  { symbol: 'RAYMOND.NS', nse: 'RAYMOND', company: 'Raymond', sector: 'Textiles' },
  { symbol: 'ARVIND.NS', nse: 'ARVIND', company: 'Arvind', sector: 'Textiles' },
  { symbol: 'VARDHMAN.NS', nse: 'VARDHMAN', company: 'Vardhman Textiles', sector: 'Textiles' },
  { symbol: 'WELSPUNIND.NS', nse: 'WELSPUNIND', company: 'Welspun India', sector: 'Textiles' },
  { symbol: 'NIITLTD.NS', nse: 'NIITLTD', company: 'NIIT', sector: 'Education' },
  { symbol: 'CARERATING.NS', nse: 'CARERATING', company: 'CARE Ratings', sector: 'Finance' },
  { symbol: 'CRISIL.NS', nse: 'CRISIL', company: 'CRISIL', sector: 'Finance' },
  { symbol: 'CDSL.NS', nse: 'CDSL', company: 'CDSL', sector: 'Finance' },
  { symbol: 'BSE.NS', nse: 'BSE', company: 'BSE Limited', sector: 'Finance' },
  { symbol: 'MCX.NS', nse: 'MCX', company: 'MCX India', sector: 'Finance' },
  { symbol: 'ANGELONE.NS', nse: 'ANGELONE', company: 'Angel One', sector: 'Finance' },
  { symbol: 'MOTILALOFS.NS', nse: 'MOTILALOFS', company: 'Motilal Oswal Financial', sector: 'Finance' },
  { symbol: 'IIFL.NS', nse: 'IIFL', company: 'IIFL Finance', sector: 'Finance' },
  { symbol: 'PNBHOUSING.NS', nse: 'PNBHOUSING', company: 'PNB Housing Finance', sector: 'Finance' },
  { symbol: 'CANFINHOME.NS', nse: 'CANFINHOME', company: 'Can Fin Homes', sector: 'Finance' },
  { symbol: 'AAVAS.NS', nse: 'AAVAS', company: 'Aavas Financiers', sector: 'Finance' },
  { symbol: 'HOMEFIRST.NS', nse: 'HOMEFIRST', company: 'Home First Finance', sector: 'Finance' },
  // Hotels & Travel
  { symbol: 'INDHOTEL.NS', nse: 'INDHOTEL', company: 'Indian Hotels (Taj)', sector: 'Hotels' },
  { symbol: 'EIHOTEL.NS', nse: 'EIHOTEL', company: 'EIH (Oberoi Hotels)', sector: 'Hotels' },
  { symbol: 'LEMONTREE.NS', nse: 'LEMONTREE', company: 'Lemon Tree Hotels', sector: 'Hotels' },
  { symbol: 'CHALET.NS', nse: 'CHALET', company: 'Chalet Hotels', sector: 'Hotels' },
  { symbol: 'MAHINDCIE.NS', nse: 'MAHINDCIE', company: 'Mahindra CIE Automotive', sector: 'Auto' },
  // Miscellaneous strong performers
  { symbol: 'ASTRAL.NS', nse: 'ASTRAL', company: 'Astral Poly Technik', sector: 'Industrials' },
  { symbol: 'SUPREME.NS', nse: 'SUPREMEIND', company: 'Supreme Industries', sector: 'Industrials' },
  { symbol: 'SUPREMEIND.NS', nse: 'SUPREMEIND', company: 'Supreme Industries', sector: 'Industrials' },
  { symbol: 'FINOLEX.NS', nse: 'FINOLEX', company: 'Finolex Industries', sector: 'Industrials' },
  { symbol: 'FINOLEXCAB.NS', nse: 'FINOLEXCAB', company: 'Finolex Cables', sector: 'Electricals' },
  { symbol: 'POLYCAB.NS', nse: 'POLYCAB', company: 'Polycab India', sector: 'Electricals' },
  { symbol: 'KEI.NS', nse: 'KEI', company: 'KEI Industries', sector: 'Electricals' },
  { symbol: 'GUJGASLTD.NS', nse: 'GUJGASLTD', company: 'Gujarat Gas', sector: 'Utilities' },
  { symbol: 'MGL.NS', nse: 'MGL', company: 'Mahanagar Gas', sector: 'Utilities' },
  { symbol: 'IGL.NS', nse: 'IGL', company: 'Indraprastha Gas', sector: 'Utilities' },
  { symbol: 'ATGL.NS', nse: 'ATGL', company: 'Adani Total Gas', sector: 'Utilities' },
  { symbol: 'GSPL.NS', nse: 'GSPL', company: 'Gujarat State Petronet', sector: 'Utilities' },
  { symbol: 'ZYDUSLIFE.NS', nse: 'ZYDUSLIFE', company: 'Zydus Lifesciences', sector: 'Pharma' },
  { symbol: 'TORNTPOWER.NS', nse: 'TORNTPOWER', company: 'Torrent Power', sector: 'Utilities' },
  { symbol: 'TTML.NS', nse: 'TTML', company: 'Tata Teleservices Maharashtra', sector: 'Telecom' },
  { symbol: 'JBCHEPHARM.NS', nse: 'JBCHEPHARM', company: 'JB Chemicals', sector: 'Pharma' },
  { symbol: 'SYNGENE.NS', nse: 'SYNGENE', company: 'Syngene International', sector: 'Pharma' },
  { symbol: 'DIVI.NS', nse: 'DIVISLAB', company: "Divi's Laboratories", sector: 'Pharma' },
  { symbol: 'ATUL.NS', nse: 'ATUL', company: 'Atul', sector: 'Chemicals' },
  { symbol: 'BASF.NS', nse: 'BASF', company: 'BASF India', sector: 'Chemicals' },
  { symbol: 'TATACHEMICALS', nse: 'TATACHEM', company: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'CHAMBLFERT.NS', nse: 'CHAMBLFERT', company: 'Chambal Fertilisers', sector: 'Chemicals' },
  { symbol: 'GNFC.NS', nse: 'GNFC', company: 'GNFC', sector: 'Chemicals' },
  { symbol: 'RCF.NS', nse: 'RCF', company: 'Rashtriya Chemicals', sector: 'Chemicals' },
  { symbol: 'COROMANDEL.NS', nse: 'COROMANDEL', company: 'Coromandel International', sector: 'Agrochem' },
  { symbol: 'GHCL.NS', nse: 'GHCL', company: 'GHCL', sector: 'Chemicals' },
  { symbol: 'EIDPARRY.NS', nse: 'EIDPARRY', company: 'EID Parry', sector: 'Agriculture' },
  { symbol: 'BALRAMCHIN.NS', nse: 'BALRAMCHIN', company: 'Balrampur Chini Mills', sector: 'Agriculture' },
  { symbol: 'RENUKA.NS', nse: 'RENUKA', company: 'Shree Renuka Sugars', sector: 'Agriculture' },
  { symbol: 'TRIVENI.NS', nse: 'TRIVENI', company: 'Triveni Engineering', sector: 'Agriculture' },
  { symbol: 'MCDOWELL-N.NS', nse: 'MCDOWELL-N', company: 'United Spirits', sector: 'FMCG' },
  { symbol: 'GLOBUSSPR.NS', nse: 'GLOBUSSPR', company: 'Globus Spirits', sector: 'FMCG' },
  { symbol: 'SONACOMS.NS', nse: 'SONACOMS', company: 'Sona BLW Precision', sector: 'Auto' },
  { symbol: 'SAMVARDHANA', nse: 'MOTHERSON', company: 'Samvardhana Motherson', sector: 'Auto' },
  { symbol: 'BIKAJI.NS', nse: 'BIKAJI', company: 'Bikaji Foods', sector: 'FMCG' },
  { symbol: 'CAMPUS.NS', nse: 'CAMPUS', company: 'Campus Activewear', sector: 'Consumer' },
  { symbol: 'NUVOCO.NS', nse: 'NUVOCO', company: 'Nuvoco Vistas', sector: 'Cement' },
  { symbol: 'STAR.NS', nse: 'STARHEALTH', company: 'Star Health Insurance', sector: 'Insurance' },
  { symbol: 'ABSLAMC.NS', nse: 'ABSLAMC', company: 'Aditya Birla Sun Life AMC', sector: 'Finance' },
  { symbol: 'HDFCAMC.NS', nse: 'HDFCAMC', company: 'HDFC AMC', sector: 'Finance' },
  { symbol: 'NIPPONLIFE.NS', nse: 'NIPPONLIFE', company: 'Nippon India AMC', sector: 'Finance' },
  { symbol: 'UTI.NS', nse: 'UTIAMC', company: 'UTI AMC', sector: 'Finance' },
  { symbol: 'UTIAMC.NS', nse: 'UTIAMC', company: 'UTI AMC', sector: 'Finance' },
  { symbol: 'MAPMYINDIA.NS', nse: 'MAPMYINDIA', company: 'MapmyIndia', sector: 'IT' },
  { symbol: 'INOXINDIA.NS', nse: 'INOXINDIA', company: 'INOX India', sector: 'Industrials' },
  { symbol: 'SIGNATURE.NS', nse: 'SIGNATURE', company: 'Signature Global', sector: 'Real Estate' },
  { symbol: 'JSWENERGY.NS', nse: 'JSWENERGY', company: 'JSW Energy', sector: 'Utilities' },
  { symbol: 'CMSINFO.NS', nse: 'CMSINFO', company: 'CMS Info Systems', sector: 'IT' },
  { symbol: 'BSOFT.NS', nse: 'BSOFT', company: 'Birlasoft', sector: 'IT' },
  { symbol: 'CYIENT.NS', nse: 'CYIENT', company: 'Cyient', sector: 'IT' },
  { symbol: 'RATEGAIN.NS', nse: 'RATEGAIN', company: 'RateGain Travel Tech', sector: 'IT' },
  { symbol: 'NSLNISP.NS', nse: 'NSLNISP', company: 'NMDC Steel', sector: 'Metals' },
  { symbol: 'JSPL.NS', nse: 'JSPL', company: 'Jindal Steel & Power', sector: 'Metals' },
  { symbol: 'TATAMETALI.NS', nse: 'TATAMETALI', company: 'Tata Metaliks', sector: 'Metals' },
  { symbol: 'TATASTEELBSL.NS', nse: 'TATASTEELBSL', company: 'Tata Steel BSL', sector: 'Metals' },
  { symbol: 'JINDALPOLY.NS', nse: 'JINDALPOLY', company: 'Jindal Poly Films', sector: 'Materials' },
  { symbol: 'UFLEX.NS', nse: 'UFLEX', company: 'UFlex', sector: 'Materials' },
  { symbol: 'HUHTAMAKI.NS', nse: 'HUHTAMAKI', company: 'Huhtamaki India', sector: 'Materials' },
]

// Remove duplicates by NSE symbol
const seen = new Set<string>()
export const NIFTY500 = STOCK_UNIVERSE.filter(s => {
  if (seen.has(s.nse)) return false
  seen.add(s.nse)
  return true
})
